# Generated by Django 4.1.4 on 2023-02-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_image_post_upvote_alter_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileadd',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='profileadd',
            name='time_line_pic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
